[package]
name = "qris-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
fast_qr = { version = "0.12.7", features = ["image"] }
image = "0.25.5"
qris = "0.1.0"
rqrr = "0.8.0"
